### ISSUE TITLE
Random state setting for splitting training and testing data

### ISSUE THREAD

**Issue by mirohu** [UBC-MDS/National_Collision_DB_Group407#2]
Hi guys! 

I was wondering if we should use the same number of random state while we splitting the training and testing data. I will go ahead and use this code for splitting!
``` 
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                              test_size=0.20, random_state=407)
```

**Comment by rita-ni** [comment]
> Hi guys!
> 
> I was wondering if we should use the same number of random state while we splitting the training and testing data. I will go ahead and use this code for splitting!
> 
> ```
> X_train, X_test, y_train, y_test = train_test_split(X, Y, 
>                               test_size=0.20, random_state=407)
> ```

Sure. We can all use the same random state then, thanks Miro!

**Comment by schepal** [comment]
Sounds good - I will note this for my train test split as well.
