### ISSUE TITLE
Feedback from Jarome and Kenneth 

### ISSUE THREAD

**Issue by vigchandra** [UBC-MDS/National_Collision_DB_Group407#44]
1. Used different classifiers and how they performed - which is cool.
2. We ran SVM but didn't mention about the time it took to run and hence abandoned it. 
3. Justification of the scoring was good and showing the accuracy.
4. Could have shown the confusion matrix alongside classification report. 
5. Could have included the EDA outputs in the final report itself. 
6. Subheading : only random forest present, nothing for logistic.

**Comment by schepal** [comment]
- We decided to keep the EDA separate from the final report to only report our predictive results
- That is a fair point for the confusion matrix - we will consider this for future iterations of our project as we currently have higher priority issues to address
- The subheading suggestion has been fixed.
