### ISSUE TITLE
Peer Feedbacks

### ISSUE THREAD

**Issue by YueJiangMDSV** [UBC-MDS/National_Collision_DB_Group407#46]
1. Might be better to include research question in the final report
2. Might be better to include one or two important graphs from EDA to explain the dataset a bit
3. The columns of the two tables in the final report are a bit confusing
4. Could have more discussion on the final results, i.e. what do the numbers/scores mean...
5. The report mentions "predictive features which cause fatal accidents" at the beginning, but was not discussed in later parts of the report

**Comment by mirohu** [comment]
Thanks for all the suggestions Yue!
We addressed most of them - added research question in the final report, included more tables and added explanations and discussion :)
