### ISSUE TITLE
Wrangling check

### ISSUE THREAD

**Issue by rita-ni** [UBC-MDS/National_Collision_DB_Group407#5]
Hello team,

below is the code I wrote for data wrangling for the inferential question. Since we need to keep only the cases where both passenger and second-row left were occupied within the same car, there are lots of wrangling to do, because the data does not have a unique identifier for each vehicle.

```import pandas as pd
import numpy as np

df = pd.read_csv('22.csv')

# subsetting columns of interest
needed_col = df[['P_PSN', 'P_ISEV', 'V_TYPE', 'C_CASE', 'V_ID']]

# filtering column values
filter_PSN = needed_col.loc[needed_col['P_PSN'].isin(['13', '21'])]
filter_V_TYPE = filter_PSN.loc[filter_PSN['V_TYPE'] == '01']
filtered = filter_V_TYPE.loc[filter_V_TYPE['P_ISEV'].isin(['1','2', '3'])]
dat = filtered.apply(pd.to_numeric)

# grouping variable into new categories
dat['row_num'] = np.where(dat.P_PSN > 20, '2', '1')
dat['fatality'] = np.where(dat.P_ISEV > 2, 'Fatal', 'Non-fatal')
final_df = dat[dat.duplicated(subset=['C_CASE', 'V_ID'], keep = False)]
```

Please check my code and let me know if the filtering looks correct to you!

Thanks!

**Comment by mirohu** [comment]
I was thinking if we should select the C_CASE and V_ID first then select the P_PSN?
